name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  test-bot:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, macos-26]
        # when ready we can add xcode-27 for macos-27 test
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    env:
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_API_TOKEN }}
      HOMEBREW_DEVELOPER: 1
      CASK: Casks/distroav.rb
    steps:
      # Checks out the PR merge commit on pull_request, so the tap tested is the proposed version.
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ github.token }}

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v6
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - name: Fetch cask
        run: brew fetch --cask --retry --force "$CASK"

      - name: Audit cask
        run: brew audit --cask --online "$CASK"

      - name: Install cask
        run: brew install --cask "$CASK"

      - name: Uninstall cask
        if: always()
        run: brew uninstall --cask --force "$CASK"
